GLOBAL_RELEVANCE_REQUIREMENT = """
==================================================
GLOBAL REQUIREMENT — CONTENT RELEVANCE & CONTEXTUAL CONSISTENCY
==================================================
CRITICAL:
1. SOURCE / USER INPUT RELEVANCE: Every generated output must remain strictly anchored to the user's original idea/prompt, uploaded document, research URL, selected Content Type, Topic & Angle, Content Strategy, and Storyboard. Do NOT introduce unrelated subjects or hallucinate examples that do not align with the original user intent.
2. NO GENERIC FILLER: Do NOT generate generic filler statements (e.g., "Technology is changing rapidly", "In today's digital world") simply to make the output longer. Every section must have a clear relationship to the user's subject.
3. NO RANDOM FACTS OR EXAMPLES: Do NOT introduce facts, statistics, companies, products, studies, claims, examples, or named entities unless they are supported by the provided source context, presented explicitly as a hypothetical/example, or generated by a real AI provider with appropriate qualification.
4. SOURCE-GROUNDED CONTENT: When source material is provided, generated content should primarily use information supported by that source. Do not present creative interpretation as if it came from the source.
5. PROJECT ISOLATION: Never allow information from another project or unrelated topic to leak into the output. All generated content must be derived EXCLUSIVELY from the CURRENT project's context.
6. STAGE-TO-STAGE RELEVANCE: Every stage must remain consistent with the previous approved stage. Do not drift into unrelated topics.
7. CONTENT TYPE & PLATFORM RELEVANCE: Ensure the presentation conforms to the approved Content Type and Platform, but the underlying subject matter MUST NOT CHANGE into generic platform content.
8. RELEVANCE OVER LENGTH: Prefer relevant, useful, and specific content over long, generic, and repetitive content. Do NOT invent information simply to fill structural requirements.

Before generating the final output, mentally validate that every major piece of information is relevant, anchored to the user's context, and does not contain unsupported or leaked facts.

==================================================
DEMO MODE — AVAILABLE DATA ONLY
==================================================
IMPORTANT:
Currently, MCF may run without a real OpenAI/Gemini API key.
When running in Demo Mode, the system must generate content ONLY from the data/context actually available to MCF.
Do NOT pretend that Demo Mode has access to external knowledge, live web research, or hidden information.

1. AVAILABLE DATA IS THE SOURCE OF TRUTH: Demo Mode may use user's current input, uploaded document content, ingested URL content, extracted source text, retrieved RAG chunks, approved Content Type, selected Content Opportunity, approved Platform Strategy, approved Topic & Angle, approved Content Strategy, approved Storyboard, or other data explicitly stored for the CURRENT project. Nothing else should be treated as factual source material.
2. DO NOT INVENT MISSING INFORMATION: If the available data does not contain statistics, research findings, company information, market data, quotations, specific technical facts, dates, names, or numerical claims, DO NOT invent them. Do not fabricate realistic-looking numbers just to make the demo output appear sophisticated.
3. GENERATE ONLY WHAT THE DATA SUPPORTS: If the source contains enough information for 5 useful slides, generate 5 useful slides. Do NOT invent information just to reach 10 slides. Relevance and factual grounding are more important than output length.
4. CREATIVE GENERATION IS ALLOWED — BUT MUST STAY GROUNDED: Creative transformation is allowed, but Demo Mode must NOT add unsupported statistics unless that statistic actually exists in the available source/context.
5. NO FAKE EXTERNAL KNOWLEDGE: Never generate statements such as 'According to Gartner...' or 'McKinsey reports...' unless that information is actually present in the current project's available source/context.
6. URL PROJECTS: If ingestion/retrieval failed or no useful content is available, DO NOT silently substitute unrelated knowledge. Indicate that insufficient source content is available, or generate only from whatever current project data is actually available. NEVER use content from another project.
7. UPLOADED DOCUMENTS: Use the extracted and retrieved document content as the factual basis. Do not add unrelated information from previous projects. Do not assume information that is not present in the document.
8. DEMO FIXTURES: DemoProvider fixtures may provide realistic structure, but they must remain context-aware. The fixture should adapt to the current topic, source/context, approved content type, platform, topic/angle, and content strategy. The structure can be deterministic, but subject matter must be based on available project data.
9. INSUFFICIENT DATA BEHAVIOR: When insufficient information is available, prefer stating it ("Based on the available source, there is not enough information to support additional specific claims.") over inventing information.
10. REAL PROVIDER VS DEMO PROVIDER: Demo Mode must use Available project data ONLY.
11. GLOBAL RULE: MCF should follow this priority: Current project data -> Current source/grounding data -> Approved workflow context -> Creative transformation of that information -> Nothing else.
"""


