"""Add user_id to project

Revision ID: 2d237471478c
Revises: cd20b6e3dd9a
Create Date: 2026-09-23 17:02:25.599726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d237471478c'
down_revision: Union[str, None] = 'cd20b6e3dd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add user_id column as nullable
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # 2. Check if a default legacy user exists, if not create one
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id FROM users WHERE email='legacy@system.local'"))
    user = result.fetchone()
    
    if user:
        legacy_user_id = user[0]
    else:
        # Create legacy user with a dummy hash
        # Not importing security to avoid dependency issues in migrations
        # Just use a dummy bcrypt hash string
        dummy_hash = "$2b$12$KIXeJ1o/XzC1A.7P8F/Fm.a0C1yA5M1e/0R7A8WbN6eYkM.Q2O4iC"
        result = connection.execute(sa.text(
            f"INSERT INTO users (email, hashed_password, is_active, is_superuser) "
            f"VALUES ('legacy@system.local', '{dummy_hash}', true, false) RETURNING id"
        ))
        legacy_user_id = result.fetchone()[0]
        
    # 3. Assign legacy_user_id to existing projects
    connection.execute(sa.text(f"UPDATE projects SET user_id = {legacy_user_id} WHERE user_id IS NULL"))
    
    # 4. Alter column to be non-nullable
    op.alter_column('projects', 'user_id', nullable=False)
    
    # 5. Add foreign key
    op.create_foreign_key('fk_projects_user_id', 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
